### ISSUE TITLE
Reports are not generating in eclipse .gets a compile error

### ISSUE THREAD

**Issue by nareshm1** [healenium/healenium-example#12]
Hi @GannaChernyshova  @LittleDecorator @DzmitryHumianiuk @KozhevnikovSergey @OleksiiYevsovych 

Hope you are all good !!

Appreciate guyzzz.. Your are awesome as whole world is running behind the payable frameworks you are providing frameworks as open source 

I am trying healenium 3.0 new version which I am running with TestNG framework .
With No command line I was able to run the test suite(directly from eclipse)  and can heal the locators but unable to generate report through this way and while running with **mvn clean test** on command line due to compiler mvn compiler error because version 1.8 is giving an error .

Could you please bring more information on the healenium 3.0.5 with TestNG and steps to generate report widely.

This could be helpful

Link to github : https://github.com/nareshm1/Self_healing_automation.git

**Comment by bhargavkumar-65** [comment]
@nareshm1 try removing <pluginmanagement> tag from pom.xml. 
weird resolution but it worked for me.

**Comment by ElenaStepuro** [comment]
Hello @bhargavkumar-65 For generating report please set up plugin under 'plugins' group. Also, you need to run test via 'mvn clean test' comand. Unfortunately, in other ways it's not working correctly.
